### ISSUE TITLE
I can't find architecture.builder-protocol.print-tree:serialize

### ISSUE THREAD

**Issue by robert-strandh** [scymtym/s-expression-syntax#1]
The README mentions architecture.builder-protocol.print-tree:serialize
in the second example, but I can't find that function, nor even the package
being mentioned.

**Comment by scymtym** [comment]
The `architecture.builder-protocol.print-tree:serialize` function is part of the [architecture.builder-protocol](https://github.com/scymtym/architecture.builder-protocol) project. When I mentioned the system in this README, I forgot that I had not yet pushed it to the architecture.builder-protocol repository. I have now pushed the system, so this issue should be solved.

**Comment by scymtym** [comment]
The system can now be found in the linked repository.
