### ISSUE TITLE
The :LAMBDA node contains a :LAMBDA-EXPRESSION rather than being one

### ISSUE THREAD

**Issue by robert-strandh** [scymtym/s-expression-syntax#15]
The :LAMBDA node ought to contain a lambda list, declarations, documentation, and body forms,
but instead it contains a :LAMBDA-EXPRESSION that contains those things.

**Comment by scymtym** [comment]
Fix in commit f5fbcf9f3ae83bcfba931f69ee1ef0cf2b523140.
