### ISSUE TITLE
Inconsistent relations for the object argument to pprint-locical-block, print-unreadable-object, and quote

### ISSUE THREAD

**Issue by robert-strandh** [scymtym/s-expression-syntax#5]
In PPRINT-LOGICAL-BLOCK and PRINT-UNREADABLE-OBJECT the node is
related to the object argument using the relation :OBJECT.

However, in QUOTE, the node is related to the object argument using
the relation :MATERIAL.

**Comment by scymtym** [comment]
The specification defines the syntax of `quote` as `quote object => object` so we should use "object".
