### ISSUE TITLE
Inconsistency in setq/psetq vs setf/psetf in the relation for  value forms

### ISSUE THREAD

**Issue by robert-strandh** [scymtym/s-expression-syntax#6]
In SETQ and PSETQ, the node is related to the value forms using the
relation :VALUE-FORM, but in PSETF and PSETQ the similar relation is
:NEW-VALUE.

**Comment by scymtym** [comment]
In summary and extending the list a bit

| Operator               | Current name        | New name      |
| `setq`                 | `:value-form`       | `:value`      |
| `psetq`                | `:value-form`       | `:value`      |
| `setf`                 | `:new-value`        | `:value`      |
| `psetf`                | `:new-value`        | `:value`      |
| `shiftf`               | `:new-value`        | `:value`      |
| `multiple-value-setq`  | - (not implemented) | `:values` (?) |
| `multiple-value-bind`  | `:values-form`      | `:values` (?) |
| `multiple-value-prog1` | `:values-form`      | `:values` (?) |
